spring.application.name=dashboard


spring.profiles.active=dev

# JPA
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.format_sql=true

# JWT Configuration
app.jwt.secret=FinanceDashboard$ecretKey@2024!VeryLongAndSecureSecretKeyFor256BitJWTSigning
app.jwt.expiration-ms=86400000

# SpringDoc / Swagger UI
springdoc.api-docs.path=/api/docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operationsSorter=method
springdoc.swagger-ui.tagsSorter=alpha
springdoc.swagger-ui.display-request-duration=true

# Server
server.port=8080
server.error.include-message=always
server.error.include-binding-errors=always


